### ISSUE TITLE
Preprocessor directives with spaces are incorrectly parsed

### ISSUE THREAD

**Issue by bartlibert** [nickdiego/compiledb-generator#12]
When the command line used to compile a file contains "-D somedefine", the generated compile_commands.json file will contain the string "-D" in the arguments array, instead of "-D somedefine".
If the command line is "-Dsomedefine", it works as expected.

I have checked gcc documentation but I have found no answer to the question of the correct way "-Ddefine" or "-D define", so if you find information that the space is actually forbidden (but tolerated), feel free to close this.

**Comment by nickdiego** [comment]
Should be fixed in the current version.
