### ISSUE TITLE
Commands parsed incorrectly when shell/bash substitution commands are used

### ISSUE THREAD

**Issue by OmegaPhil** [nickdiego/compiledb-generator#13]
I'm currently working on clang static analysis capability with an autotools codebase, so thanks for this tool to plug the compilation database hole!

This is probably an unusual thing, but in my inherited project there are some macros for paths [which are speechmark-delimited](https://git.xfce.org/panel-plugins/xfce4-hardware-monitor-plugin/tree/src/Makefile.am#n44): HARDWARE_MONITOR_GLADEDIR and PACKAGE_LOCALE_DIR:

```
libhardwaremonitor_la_CPPFLAGS = \
                        -DHARDWARE_MONITOR_GLADEDIR=\""$(gladedir)/"\" \
                        -DPACKAGE_LOCALE_DIR=\"$(localedir)\" \
                        @LIBXFCE4PANEL_CFLAGS@ \
                        @LIBXFCE4UI_CFLAGS@
```

in compile_commands.json these result in:

```
"-DHARDWARE_MONITOR_GLADEDIR=\\\"\"/usr/local/share/xfce4-hardware-monitor-plugin/glade/\"\\\"",
"-DPACKAGE_LOCALE_DIR=\\\"/usr/local/share/locale\\\"",
```

The resultant clang-tidy call does not consider these macros as defined when they are referenced in code.  Doing the following replacements fixes it:

```
\\\"\" -> \"
\"\\\" -> \"
\\\" -> \"
```

Saying this, I don't think there is a particular need for speechmark-delimiting paths here since a number of other things in the build system cannot cope with spaces in my experience, so I'll remove that from my project - just noting here in case someone eventually has a good reason for them.

Similar to [this bug](https://github.com/nickdiego/compiledb-generator/issues/6), it looks like the relative paths for source files are mangled at the start - the backtick completely breaks things here:

```
  "'./'`bar-view.cpp"
  ], 
  "file": "'./'`bar-view.cpp"
```

Not sure where this is coming from.

Anyway, after find&replacing, I was able to get clang-tidy analysing the code :) scan-build doesn't work but luckily it isn't needed.

**Comment by OmegaPhil** [comment]
Removing the speechmarks broke the build, so I guess they are required and this is a real bug...

**Comment by nickdiego** [comment]
Thanks for reporting this.
Indeed, autotools generate some very tricky makefile commands, most of them using some "bash magic".

Although in this particular case simple replace regex operations seems to solve the issue, I need to implement some unit tests as the parsing complexity is increasing, so the we can make sure we're not adding some regressions to the parser code. So, the fix can be delayed a little bit.

BTW, patches are welcome :)

**Comment by nickdiego** [comment]
> Similar to this bug, it looks like the relative paths for source files are mangled at the start - the backtick completely breaks things here:
> 
> ```
> "'./'`bar-view.cpp"
>   ], 
>   "file": "'./'`bar-view.cpp"
> ```
> Not sure where this is coming from.

About this one, I guess it happens for this kind of make rules:
https://github.com/nickdiego/compiledb-generator/issues/6#issuecomment-345876057

Anyway, I'll try to address this issue soon, not sure if  there will be some clean/non-hacking solution :(

**Comment by OmegaPhil** [comment]
Here is the workaround I use atm to fix the json file:

sed -i "s^'./'\`^^g" compile_commands.json; sed -i 's/\\\\\\\"\\\"/\\"/g; s/\\"\\\\\\"/\\"/g; s/\\\\\\"/\\"/g;' compile_commands.json

I had to break into 2 sed commands as the quote meant bash weak quoting was required, which would have resulted in a real escaping mess.

If this problem wasn't two things removed from my main task, yes I'd hack on it ;) As it is this is my first experience of clang.

Sure, will report separately.

**Comment by OmegaPhil** [comment]
Here is the relevant target in the produced makefile:

```
libhardwaremonitor_la_CPPFLAGS = \
                        -DHARDWARE_MONITOR_GLADEDIR=\""$(gladedir)/"\" \
                        -DPACKAGE_LOCALE_DIR=\"$(localedir)\" \
                        -pthread -I/usr/include/xfce4/libxfce4panel-1.0 -I/usr/include/gtk-2.0 -I/usr/l
ib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pa
ngo-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/
usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/
usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/xfce4 -I/usr/include/glib-2.0 -I/usr/lib/
x86_64-linux-gnu/glib-2.0/include \
                        -pthread -I/usr/include/xfce4/libxfce4ui-1 -I/usr/include/gtk-2.0 -I/usr/lib/x8
6_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1
.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/i
nclude/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/i
nclude/pango-1.0 -I/usr/include/freetype2 -I/usr/include/xfce4 -I/usr/include/glib-2.0 -I/usr/lib/x86_6
4-linux-gnu/glib-2.0/include
```

Output of 'make -Bnkw' for one of the binaries being compiled:

```
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -DHARDWARE_MONITOR_GLADEDIR=\""/usr/share/xfce4-hardware-monitor-plugin/glade/"\" -DPACKAGE_LOCALE_DIR=\"/usr/share/locale\" -pthread -I/usr/include/xfce4/libxfce4panel-1.0 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/xfce4 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/xfce4/libxfce4ui-1 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/xfce4 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -pthread -I/usr/include/gtkmm-2.4 -I/usr/lib/x86_64-linux-gnu/gtkmm-2.4/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-unix-print-2.0 -I/usr/include/gtk-2.0 -I/usr/include/gdkmm-2.4 -I/usr/lib/x86_64-linux-gnu/gdkmm-2.4/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gail-1.0 -I/usr/include/libart-2.0 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libgtop-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libgnomecanvasmm-2.6 -I/usr/lib/libgnomecanvasmm-2.6/include  --std=c++11 -g -O2 -c -o libhardwaremonitor_la-choose-monitor-window.lo `test -f 'choose-monitor-window.cpp' || echo './'`choose-monitor-window.cpp
```

So it looks like libtool is doing something odd here at the end (I only have basic autotools progression so this isn't something I can talk about or get into).

I'm just a user passing by to get at clang static analysis output on this codebase, I don't use clang otherwise - so beyond removing the speechmarks (which failed), I wouldn't be editing the build system just for this.

**Comment by lyonlh** [comment]
@OmegaPhil 

Thank you for the detailed information.

I figure out that the `backslash` and `double-quote` in the `Makefile` is for `shell quotation`, and under this condition`compiledb-generator` adds additional when dump to output using `json.dump`. So the solution I recommended is, run `make` without the `dry-run` option `-n` in order to let `shell` consume the quotes just for it. 

Could you please try the below command again:
`make -Bkw | compiledb-gen-parser -o compile_commads.json`
and check whether it works well?

**Comment by OmegaPhil** [comment]
Nope, still the same:

```
   "-DHARDWARE_MONITOR_GLADEDIR=\\\"\"/usr/share/xfce4-hardware-monitor-plugin/glade/\"\\\"", 
   "-DPACKAGE_LOCALE_DIR=\\\"/usr/share/locale\\\"", 

   "'./'`bar-view.cpp"
  ], 
  "file": "'./'`bar-view.cpp"
 }, 
```

**Comment by lyonlh** [comment]
@OmegaPhil 

The root cause is `make` echoes the raw commands by default, so that the output of `make` contains both the no-interpreted and interpreted commands. If I didn't guess wrong, the right items are also in the compilation database file. The last step we should do is to keep `make` silent by feeding it `-s` option :smile: 
`make -sBkw | compiledb-gen-parser -o compile_commands.json`

**Comment by OmegaPhil** [comment]
Good call - with the unchanged compile_commands.json from the last test:
```
$ grep 'bar-view.cpp' compile_commands.json
   "'./'`bar-view.cpp"
  "file": "'./'`bar-view.cpp"
   "bar-view.cpp"
  "file": "bar-view.cpp"
```
Regenerating the database via the new call only results in one output of bar-view (etc), which just leaves the speechmarks issue:
```
   "-DHARDWARE_MONITOR_GLADEDIR=\\\"/usr/share/xfce4-hardware-monitor-plugin/glade/\\\"", 
   "-DPACKAGE_LOCALE_DIR=\\\"/usr/share/locale\\\"", 
```

**Comment by lyonlh** [comment]
@OmegaPhil 

It's time to let `shell` do the last work. Tiger `shell`' with XTRACE to print out the interpreted commands.

`make -sBkw SHELL='sh -x' |& sed -n -e '/^\+ sh -x/p' -e '/^make/p' | ~/Tools/compiledb-generator/compiledb-gen-parser -o compile_commands.json`

**Comment by OmegaPhil** [comment]
Yes, this works - speechmarks are dealt with too now - thanks.
