### ISSUE TITLE
Compiler detection regex will have false positives

### ISSUE THREAD

**Issue by seabadger** [nickdiego/compiledb-generator#16]
The regex for finding the compiler invocation will find non-compilation lines that, for instance, happen to run a command that has something like gcc as an argument , or a switch name (or even part of a switch name).

Not sure how to solve this fully short of parsing shell syntax, but the regex can be tighter than it is now.

**Comment by lyonlh** [comment]
@seabadger 
I have wrote a new tool named [Mint](https://github.com/lyonlh/Mint). Mint intercept the implicit variable CC and CXX to retrieve the compile commands, so that there would be not the noisy non-compilation lines. You can give it a try.

**Comment by nickdiego** [comment]
Should be fixed in the current version.
