### ISSUE TITLE
Include --sysroot=.* in flags_whitelist

### ISSUE THREAD

**Issue by daniel6651** [nickdiego/compiledb-generator#19]
Hi

In a test project I have a different sysroot set and discovered that the generated compile_commands file doesn't currently include that flag.
I use the generated file for running clang-tidy and for that to work I need the --sysroot set correctly in compile_commands.
I did a test with adding --sysroot=.* in flags_whitelist myself and that seems to do the trick.

So could you please do that update?

Cheers,

Daniel

**Comment by nickdiego** [comment]
Done.
Thanks for reporting this.
