### ISSUE TITLE
Restructure as python module

### ISSUE THREAD

**Issue by nickdiego** [nickdiego/compiledb-generator#27]

**Comment by agnjunio** [comment]
I'm gonna implement the setup.py of the project to publish in pypi.org

**Comment by nickdiego** [comment]
> I'm gonna implement the setup.py of the project to publish in pypi.org

Ok :+1:

**Comment by nickdiego** [comment]
[compdb](https://github.com/Sarcasm/compdb/blob/master/setup.py) seems to be a good reference to this task :)

**Comment by agnjunio** [comment]
http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation

Please take a look here and see which scripts we want to expose and what modules they will call respectively. I will only add the parser which we already modularized, but I think that we'll need to do this for the others too.
