### ISSUE TITLE
Slow parsing with automake-generated Makefiles 

### ISSUE THREAD

**Issue by nickdiego** [nickdiego/compiledb-generator#35]
`compiledb make` wrapper currently uses the `-B / --always-make` option to gather compile commands without having to execute an actual clean build. For automake-generated Makefiles, this option leads to very long parsing time, caused by `configure` script being executed for every make target.

Currently, to work around this issue, one can use a separate temporary build directory (to avoid clean build - useful for huge codebases) and execute make without -B option, for example:

```bash
$ export LANG=C.UTF-8
$ mkdir build-tmp && cd build-tmp && ../configure
$ make -nwk | compiledb
```

**Comment by lyonlh** [comment]
I recommend you to use `make clean` instead `-B` in the wrapper file accordingly.
