### ISSUE TITLE
Bug on row 67 in parser?

### ISSUE THREAD

**Issue by daniel6651** [nickdiego/compiledb-generator#4]
Hi

On row 67 in compiledb-gen-parser, include_path_prefix is given as both second and third argument to parse_flags:
        (count, skipped, compile_db) = parse_flags(build_log, include_path_prefix, include_path_prefix)

But second argument to parse_flags is proj_dir:
        def parse_flags(build_log, proj_dir, inc_prefix):    

So shouldn't row 67 be changed to send in proj_dir as second argument instead?

As it is now I get:
 "directory": null, 
in all of the generated entries.

Doing the proposed change locally produces the result I expect.

Cheers,

Daniel

**Comment by nickdiego** [comment]
Hi, thanks for reporting this issue..

Looks like you're right. Probably didn't get this, because I've tested most of the time with docker-based AOSP build env, where I've used/introduced --include-prefix to force include paths prefix pointing to host paths.. 

Can you send the pull request?

**Comment by daniel6651** [comment]
Hi

I sent a pull request a while ago on this. Could you have a look at it?

Cheers,

Daniel

**Comment by nickdiego** [comment]
Thanks!
