### ISSUE TITLE
Win32 assert should be removed

### ISSUE THREAD

**Issue by lucazader** [nickdiego/compiledb-generator#43]
Hi there,

Just found this awesome project!

I am using a windows dev system and have tested compiledb in the following cases:
Test steps:

1. `pip install compiledb`
2. Comment out `assert not sys.platform.startswith("win32")` in `site-packages/compiledb/cli.py`
3. Call `compiledb make` from the relevant shell.

Results:
- Windows Subsystem for Linux: Using `arm-none-eabi-gcc` and `makefiles`
    - No issues.
    - Generates the compile_commands with the WSL directory style "/mnt/c/' this mean that if you want to use the generated commands in say vscode in windows, vscode cant actually find the files. However this is a limitation with how WSL is implemented and is a side effect of using WSL for anything. It is not any fault of compiledb
- MSYS3 MINGW32 shell: Using `xtensa-esp32-elf-gcc` and `makefiles`
    - No issues.
    - Again generates the compile_commands with the directory style "/c/" which cant be used by programs inside windows like vscode
- Windows CMD: Using `arm-none-eabi-gcc` and `makefiles`
    - No issues.
    - Generates compile commands that are compatible with windows programs, like vscode

My recommendation is that you should be able to remove the `assert not sys.platform.startswith("win32")` line from cli.py to enable compiledb to work on all platforms.

Please let me know if you would like me to do any more tests, provideo you with the output compile_commands.json files, or anything else.

**Comment by nickdiego** [comment]
Hi @lucazader , thanks for testing and reporting this. Nice to know it's working ok on Windows/WSL platform.

Feel free to send a PR fixing this :)

**Comment by lucazader** [comment]
Hi @nickdiego 

Sounds good. I have forked and made the PR.
Ping me if you need any WIP or future versions or features tested.

**Comment by agnjunio** [comment]
Attaching PR #45
