### ISSUE TITLE
Doesn't emit subdir.

### ISSUE THREAD

**Issue by ryosa** [nickdiego/compiledb-generator#6]
In the output file, "directory" contains only the project root, not the full path to "file". Then `scan-buld` does nothing.

**Comment by lyonlh** [comment]
@ryosa, file path is at "file" field. I guess the reason scan-build does nothing is the project-root path is not absolute. I've opened a pull request to solve this problem.

**Comment by nickdiego** [comment]
@ryosa Yeah, currently _directory_ is always set to PROJ_DIR cmd line option. _directory_ is expected to be the build working dir at the point that _compilation unit_ was compiled [[1]](https://clang.llvm.org/docs/JSONCompilationDatabase.html#format)

The right way to solve this problem actually would be to process the the make messages about "directory changing", and use that to set "directory" property.
I'll to fix that soon.

Thanks for reporting.

**Comment by nickdiego** [comment]
> @ryosa, file path is at "file" field. I guess the reason scan-build does nothing is the project-root path is not absolute. I've opened a pull request to solve this problem.

Not sure if that would solve this problem. Probably this is happening because the build system is using relative paths (relative to the current building dir) to the source files.

@ryosa can you please provide some log of your build and maybe some other infos (build system used, etc.) ??

**Comment by ryosa** [comment]
@nickdiego  I use _analyze-build_ of clang 3.4, not _scan-build._ Sorry to confuse you.
I can provide you with a part of build log, but the server's default language is Japanese and the messages of _make_ are not English. Is that alright with you?

**Comment by nickdiego** [comment]
@ryosa Ok. I think you can use `LANG=C` before your make command to force the output to be in english. Actually, I think `compiledb-parser` expects it to be in english, not sure. 

example command:

```bash
LANG=C make all
```
Thanks

**Comment by lyonlh** [comment]
@nickdiego You're right. I've create a new pull request which leverage make --print-directory option to get the subdir and put it into "directory" field.
@ryosa Maybe this is the solution.

**Comment by nickdiego** [comment]
@ryosa As #8 has been merged, please check if it solves this issue.

**Comment by ryosa** [comment]
@nickdiego @lyonlh Thanks. But #8 didn't solve the issue. Below is a part of build log.
<pre>
 make[4]: Entering directory `/root/ymph3/src/syssrc/drv'
 cd ../../.. && make  am--refresh
 make[5]: Entering directory `/root/ymph3'
 make[5]: Nothing to be done for `am--refresh'.
 make[5]: Leaving directory `/root/ymph3'
 make[5]: Entering directory `/root/ymph3'
 make[5]: Nothing to be done for `am--refresh'.
 make[5]: Leaving directory `/root/ymph3'
 cd ../../.. && make  am--refresh
 make[5]: Entering directory `/root/ymph3'
 make[5]: Nothing to be done for `am--refresh'.
 make[5]: Leaving directory `/root/ymph3'
 cd ../../.. && make  am--refresh
 make[5]: Entering directory `/root/ymph3'
 make[5]: Nothing to be done for `am--refresh'.
 make[5]: Leaving directory `/root/ymph3'
 make[5]: Entering directory `/root/ymph3'
 make[5]: Nothing to be done for `am--refresh'.
 make[5]: Leaving directory `/root/ymph3'
</pre>

After emitted the above, _make_ begins to compile the source files in /root/ymph3/src/syssrc/drv, then _directory_ in the output file is /root/ymph3 only, and that's exactly the same as before.

BTW, I altered the last line of _compiledb-gen-make_ like below.

> LANG=en_US.UTF-8 make -Bnkw "${make_opts[@]}" | $parser_cmd "${parser_opts[@]}"

**Comment by nickdiego** [comment]
I don't see any "compilation command" in this log.
Do you have some compile command example?
We need that to try to figure out why it's not generating the expected output.

**Comment by nickdiego** [comment]
>make[5]: Nothing to be done for `am--refresh'.

Looks like there's some checking (maybe from _automake_, looks like you're using autotools as build system) which overrides the behavior of "make -B", what should force all the targets to be executed unconditionally.
I think you have 2 options to workaround this:
1. Try clean build (you can use a separate build dir if your build system supports shadow building, e.g: `mkdir build2 && cd build2 && configure .. && compiledb-make -o compile_commands.json`
2. Check if automake provide some option similar to `make --always-make`, and use that to force it to show the exact compile commands for all source files.

**Comment by ryosa** [comment]
@nickdiego Here is a command line to compile /root/ymph3/src/syssrc/drv/DevInit.cpp

> /opt/timesys/toolchains/x86_64-linux-463/core2duo/toolchain/bin/ccache /opt/timesys/toolchains/x86_64-linux-463/core2duo/toolchain/bin/x86_64-timesys-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../.. -I. -I../inc -I../..//inc -I../..//config -I../..//../OSWrapper/h -I/LinuxX86_64-Haswell/usr/src/linux-3.10.5/usr/include -I/LinuxX86_64-Haswell/usr/src/linux-3.10.5/include -I/LinuxX86_64-Haswell/usr/src/linux-3.10.5/arch/x86/include -I/LinuxX86_64-Haswell/usr/local/libcont/5th/20170601/nicfum -I/LinuxX86_64-Haswell/usr/local/libcont/5th/20170601/nicfum/MES_include -I/LinuxX86_64-Haswell/usr/local/libcont/5th/20170601/nicfum/MES_include/mes -I/LinuxX86_64-Haswell/usr/local/include -I/LinuxX86_64-Haswell/usr/local/include/intel -I../..//../modules/3.10.5 -I../..//ipsrc/IPparameters -I../..//ipsrc/IPparameters/forPMS -I../..//ipsrc/inc -I../..//syssrc/inc -I../..//syssrc/commonapi/lib/rsa/MES_include/soc/mes -I../..//syssrc/commonapi/system/dbg -I../..//syssrc/commonapi/ -I../..//syssrc/application/mfp/ -I../extdrv -I../..//../IpLib/IpCommonComponent/inc -I../..//../IpLib/IpDeviceComponent/inc -I../..//../IpLib/IpTaskComponent/inc -I ../../ipsrc/PMS/inc -I ../../ipsrc/PMS/Log   -g -O2 -Wall -Wno-deprecated-declarations -Wno-trigraphs -Wno-unused-but-set-variable -fomit-frame-pointer -fno-strict-aliasing -fno-common -fsigned-char -pipe -Wno-uninitialized -Wno-conversion-null  -Werror  -D_REENTRANT -D_PTHREADS -DLYNXOS -DLINUX -DSSLC_SMALL_CODE -DNO_SOFTWARE_CRYPTO -DTORNADO -DDEF_PPSystem -DDEF_ENGINE -DDEF_SupportSSD -DDEF_IWSCOPYJOB -DDEF_Soc1200 -DPMS_PP  -g -O2 -MT DevInit.o -MD -MP -MF .deps/DevInit.Tpo -c -o DevInit.o DevInit.cpp

Yes, the project utilizes _automake_. I would have to _make clean_ then build to generate Makefiles, which takes 6 hours...

**Comment by lyonlh** [comment]
@ryosa @nickdiego 
Sorry, it's my bug introduced in [#8](https://github.com/nickdiego/compiledb-generator/pull/8).
After investigated the build log and pared it by the parser, I figured out that the regex mismatched cause of head white-space. I fix it in pull request [#9](https://github.com/nickdiego/compiledb-generator/pull/9).
Please try again.

Thanks.

**Comment by ryosa** [comment]
@lyonlh #9 looks good. Thanks a lot.

But checking the output json, I had a question, that is, relative path is included in 'file'. Here is an example.

<pre>
  "directory": "/root/ymph3/src/ipsrc/IPparameters/forCps2010", 
  "arguments": [
   "c++", 
   "-DHAVE_CONFIG_H", 
   "-I.", 
   "-I../../../..", 
   "-I.", 
   "-I../inc", 
   "-I../../..//inc", 
   "-I../../..//config", 
   "-I../../..//../OSWrapper/h", 
   "-I/LinuxX86_64-Haswell/usr/src/linux-3.10.5/usr/include", 
   "-I/LinuxX86_64-Haswell/usr/src/linux-3.10.5/include", 
   "-I/LinuxX86_64-Haswell/usr/src/linux-3.10.5/arch/x86/include", 
   "-I/LinuxX86_64-Haswell/usr/local/libcont/5th/20170601/nicfum", 
   "-I/LinuxX86_64-Haswell/usr/local/libcont/5th/20170601/nicfum/MES_include", 
   "-I/LinuxX86_64-Haswell/usr/local/libcont/5th/20170601/nicfum/MES_include/mes", 
   "-I/LinuxX86_64-Haswell/usr/local/include", 
   "-I/LinuxX86_64-Haswell/usr/local/include/intel", 
   "-I../../..//../modules/3.10.5", 
   "-I../../..//ipsrc/IPparameters", 
   "-I../../..//ipsrc/IPparameters/forPMS", 
   "-I../../..//ipsrc/inc", 
   "-I../../..//syssrc/inc", 
   "-I../../..//syssrc/commonapi/lib/rsa/MES_include/soc/mes", 
   "-I../../..//syssrc/commonapi/system/dbg", 
   "-I../../..//syssrc/commonapi/", 
   "-I../../..//syssrc/application/mfp/", 
   "-I../../..//../IpLib/IpCommonComponent/inc", 
   "-I../../..//../IpLib/IpDeviceComponent/inc", 
   "-I../../..//../IpLib/IpTaskComponent/inc", 
   "-I..", 
   "-I", 
   "../../PMS/inc", 
   "-I", 
   "../../PMS/Log", 
   "-Wall", 
   "-Wno-deprecated-declarations", 
   "-Wno-trigraphs", 
   "-Wno-unused-but-set-variable", 
   "-Wno-uninitialized", 
   "-Wno-conversion-null", 
   "-Werror", 
   "-D_REENTRANT", 
   "-D_PTHREADS", 
   "-DLYNXOS", 
   "-DLINUX", 
   "-DSSLC_SMALL_CODE", 
   "-DNO_SOFTWARE_CRYPTO", 
   "-DTORNADO", 
   "-DDEF_PPSystem", 
   "-DDEF_ENGINE", 
   "-DDEF_SupportSSD", 
   "-DDEF_IWSCOPYJOB", 
   "-DDEF_Soc1200", 
   "-DPMS_PP", 
   "-c", 
   "'./'`HardwareDriver/ddVirtualVD.cpp"
  ], 
  "file": "'./'`HardwareDriver/ddVirtualVD.cpp"
</pre>

Does this affect clang's behavior?

**Comment by ryosa** [comment]
Clang seems to understand relative path in 'file'. It didn't output error for the 'command' and 'file' in question.

**Comment by lyonlh** [comment]
@ryosa But it seems weird, there are some quote in the file field, the file path is retrieved from build log and should not be add additional characters. Could you please provide some build logs? So I can check this issue.
Thanks.

**Comment by nickdiego** [comment]
> "file": "'./'`HardwareDriver/ddVirtualVD.cpp"

Yeah, as @lyonlh said, thia one for example is pretty weird. We need to see the exact log line thelat generated this entry to try to figure it out why this is happaning.

thanks

**Comment by nickdiego** [comment]
Also, i think this particular issue is already solved. Thanks to @lyonlh and @ryosa por reporting it. So I'll close this and this escaping related issue can be open and we can move the discussion to it.

**Comment by ryosa** [comment]
The quotes in 'arguments' and 'file' were due to description in Makefile.

> ddVirtualVD.o: HardwareDriver/ddVirtualVD.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ddVirtualVD.o -MD -MP -MF $(DEPDIR)/ddVirtualVD.Tpo -c -o ddVirtualVD.o `test -f 'HardwareDriver/ddVirtualVD.cpp' || echo '$(srcdir)/'`HardwareDriver/ddVirtualVD.cpp

As long as clang properly deals with this, there's no reason to open a new issue.
Thanks guys!
